language: java
sudo: required
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script: mvn verify -B --settings mavenSettings.xml
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then mvn deploy --settings mavenSettings.xml; fi
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
