# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - name: Build with Maven
      run: mvn --update-snapshots clean verify 
    - name: Release
      uses: mg-smartrent/github-actions-maven-release@v1.5
      with:
        release-branch-name: "master"
        git-release-bot-name: "ReleaseBot"
        git-release-bot-email: "vatbub123+github@googlemail.com"
        access-token: ${GITHUB_TOKEN}
        
        # Publish artifacts to GitHub Packages
        maven-publish-args: "--update-snapshots -Dskip.unit.tests=true -Dskip.integration.tests=true"
        maven-release-publish: "true"
        maven-snapshot-publish: "true"
    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
        
        
