# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt-hotspot'
      - name: Import GPG Keys
        run: |
          if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEY | $GPG_EXECUTABLE --import; fi
          if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNER_TRUST | $GPG_EXECUTABLE --import-ownertrust; fi
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Print maven version
        run: mvn -v
      - name: Build with Maven
        run: mvn --update-snapshots clean verify -B --settings mavenSettings.xml
      - name: Release
        run: mvn --update-snapshots deploy -Dskip.unit.tests=true -Dskip.integration.tests=true -B --settings mavenSettings.xml
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
